---
# This will cause pre-commit to stop executing hooks after the first failure
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      - name: Check no large files added to repository
        id: check-added-large-files
      - name: Check branch naming convention
        id: no-commit-to-branch
        args: ['--pattern', '^(?!(([0-9]{1,})\/[a-zA-Z0-9\-]+)$).*']

# ----------------
  # commit-msg hook
  # ----------------
  # Ensure commit messages conform the conventionsl-commits standard
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [ breaking, ci, docs, feat, fix, perf, refactor, style, test, chore, revert, debug, improvement, security, wip ] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]